### ISSUE TITLE
CSG Operations not working

### ISSUE THREAD

**Issue by andybest** [davidson16807/relativity.scad#10]
Hi,

I'm using the 2015.03 release of OpenSCAD and I can't seem to get any of the CSG examples working. I've attached a screenshot to show what's happening.

<img width="1001" alt="screen shot 2016-09-06 at 15 58 52" src="https://cloud.githubusercontent.com/assets/1089613/18278787/416e1e3a-744b-11e6-8aaf-f061eaf70d52.png">

Is there anything that I'm doing wrong?

Thanks

**Comment by davidson16807** [comment]
Thanks for letting me know. There was a recent hotfix for #7 and it looks like it completely broke the CSG styling. I've disabled the hotfix and the example appears to work. Download, try again, and let me know how it goes.

**Comment by andybest** [comment]
Hey, everything seems to work now, apart from 'differed', which gives the following result:

<img width="1077" alt="screen shot 2016-09-06 at 21 20 53" src="https://cloud.githubusercontent.com/assets/1089613/18289596/e9cd44c6-7477-11e6-927f-ac40b1ebf471.png">

**Comment by davidson16807** [comment]
Try building with F6.

**Comment by andybest** [comment]
Derp. Sorry about that! All working fine :)

**Comment by davidson16807** [comment]
Thanks for letting me know. Closing.
