### ISSUE TITLE
Don't echo version on export

### ISSUE THREAD

**Issue by akaleeroy** [davidson16807/relativity.scad#14]
If echoing the version on export isn't essential I would suggest to remove it.

I came across an issue where I was [trying to set up git hooks](https://gist.github.com/akaleeroy/cf011d820b92f527044d2754821aa541) and because of that echo the command's exit code is non-zero and the commit fails.

**Comment by davidson16807** [comment]
done: 226d6183e2907bd33a5a698dc560cc7764991848
