### ISSUE TITLE
WARNING: len() parameter could not be converted

### ISSUE THREAD

**Issue by jumbojing** [davidson16807/relativity.scad#18]
include <relativity.scad>
box(50, anchor=[0,0,-1])
align([0,1,0])
orient([0,1,1])
rod(d=50, h=50, anchor=[0,0,-1]);

WARNING: len() parameter could not be converted, in file C:/Users/1/Documents/OpenSCAD/libraries/relativity.scad, line 918
WARNING: len() parameter could not be converted, in file C:/Users/1/Documents/OpenSCAD/libraries/relativity.scad, line 868
WARNING: len() parameter could not be converted, in file C:/Users/1/Documents/OpenSCAD/libraries/relativity.scad, line 887
WARNING: len() parameter could not be converted, in file C:/Users/1/Documents/OpenSCAD/libraries/relativity.scad, line 887

Why???

OpenSCAD version 2019.05

**Comment by aleung** [comment]
Basically, you need to make replacement using [type test functions](https://en.wikibooks.org/wiki/OpenSCAD_User_Manual/Type_Test_Functions):
- `len(x)==undef` ==> `!is_list(x)`
- `x==undef` ==> `is_undef(x)`

For example:
``` scad
module align(anchors, bounds="box"){
	// anchors = len(anchors.x)==undef && anchors.x!= undef ? [anchors] : anchors;
	anchors = is_undef(anchors.x) || is_list(anchors.x) ? anchors : [anchors];
```

**Comment by davidson16807** [comment]
I've confirmed this works as of merging @aleung's branch, thanks again @aleung for the help and sorry it's taken so long to get to this.
