### ISSUE TITLE
warning when loading strings.scad - even when doing nothing

### ISSUE THREAD

**Issue by hchybz** [davidson16807/relativity.scad#19]
include <C:\Users\herve\Downloads\openscad-2019.05\libraries\relativity.scad\strings.scad>
cube(10);

Console throw 

Parsing design (AST generation)...
Saved backup file: C:/Users/herve/Documents/OpenSCAD/backups/unsaved-backup-FQfmFakr.scad
Compiling design (CSG Tree generation)...
WARNING: Too many unnamed arguments supplied, in file openscad-2019.05/libraries/relativity.scad/strings.scad, line 820
WARNING: Too many unnamed arguments supplied, in file openscad-2019.05/libraries/relativity.scad/strings.scad, line 820
WARNING: Too many unnamed arguments supplied, in file openscad-2019.05/libraries/relativity.scad/strings.scad, line 820
WARNING: Too many unnamed arguments supplied, in file openscad-2019.05/libraries/relativity.scad/strings.scad, line 820
WARNING: Too many unnamed arguments supplied, in file openscad-2019.05/libraries/relativity.scad/strings.scad, line 820
Compiling design (CSG Products generation)...
Geometries in cache: 1
Geometry cache size in bytes: 728
CGAL Polyhedrons in cache: 0
CGAL cache size in bytes: 0
Compiling design (CSG Products normalization)...
Normalized CSG tree has 1 elements
Compile and preview finished.
Total rendering time: 0 hours, 0 minutes, 0 seconds

**Comment by disco0** [comment]
2019.05 throws in console when receiving unnamed arguments, specifically in `join` in both `relativity.scad` and `strings.scad` on this last line:

```` scad
function join(strings, delimeter="") = 
	strings == undef?
		undef
	: strings == []?
		""
	: _join(strings, len(strings)-1, delimeter, 0);
```` 

(BerkeleyTrue's fork)[https://github.com/BerkeleyTrue/relativity.scad] seems to fix the problem—I've merged it into my personal repo to test, and copied it to `strings.scad` if you're looking for a fix in the meantime

**Comment by davidson16807** [comment]
Okay thanks for pointing that out! Looks like this was just a nonbreaking oversight that OpenSCAD hadn't run any checks for in previous versions. Commit 71bc66 fixes the issue.
