### ISSUE TITLE
Suggestion - Orient

### ISSUE THREAD

**Issue by GilesBathgate** [davidson16807/relativity.scad#3]
I wondered if you could make use of this more generalised version of orient ;)

``` c#
module orient(a,b) {
    angle=acos((a*b)/(norm(a)*norm(b)));
    rotate(a=angle,v=cross(a,b))
        children();
}
```

where a and b are vectors.

**Comment by davidson16807** [comment]
Hi Giles. :)

Took me a while to see what you mean, but I think that could be useful. Was there any use case you have in mind or is it more for sake of completeness?

**Comment by GilesBathgate** [comment]
@davidson16807 Since all the standard primitives are orientated along the z-axis, the most useful case is to set ```a=[0,0,1]``` in which case the behaviour is the same as your existing ```orient()``` module. The case where it may be useful is when you import an STL orientated to some arbitrary axis, and you want to orient it to some other arbitrary axis. Aside from that and completeness, I just liked it for being succinct, so I thought I would share it.

**Comment by davidson16807** [comment]
I'll include this in the next release. I'm currently distracted with the peg parser I plan to add to strings.scad. 

There's also a few considerations that need to be made when working this into existing code. The rotation needs to be stored if the library is to retain the $parent_bounds special variable. Another consideration is the current method signature for orient, which allows a series of rotated copies to be created in a manner similar to rotated(). I plan not to extend this functionality to the new parameter. An example invocation might look like this:

    orient(new=[[1,6,8], [0,7,1], [6,8,0]], old=[0,0,1])

**Comment by GilesBathgate** [comment]
I think you would still need the roll parameter too.

maybe it would just be cleaner to name this new function ```orient_to()```

**Comment by davidson16807** [comment]
Correct, `roll` parameter would stay by default. 

I still like the idea for passing lists of vectors - it keeps method signatures consistent with `rotated()`,  `translated()`, and `aligned()`. It's old functionality from before when I had a cohesive vision for the library but I'm still assuming people find it useful (I will take feedback on this though). Actually, the same could be said for `orient()`, but I think the function offers another way to look at rotations that's still useful.

There could still be use in replacing `orient()`. IIRC, it's very hard to predict what value to set for `roll`. It takes a minimum of two axes to define a rotation in 3d space, but `orient()` only lets you specify one axis. The position of the other axis can be controlled using `roll`, but `roll` is only an angle offset from the default position, and the default position of that axis is not made clear. I think any replacement for `orient()` should address this issue.

I'd tend towards `oriented()` for the new function name - single word, plus it fits with the existing convention for other functions in the library.

**Comment by GilesBathgate** [comment]
Heh ```oriented()```, is also less likely to be confused with the countries of Asia, i.e. the orient ;)
